### ISSUE TITLE
Switch Test Libraries

### ISSUE THREAD

**Issue by rufer7** [dfch/biz.dfch.CS.Testing#2]
**TODOs**
* [x] Remove `Microsoft.VisualStudio.QualityTools.UnitTestFramework`
* [x] Add `Microsoft.VisualStudio.TestPlatform.TestFramework`
* [x] Update version of .NET target framework
* [x] Check, if the following files have to be adjusted
  * [x] `NOTICE`
  * [x] `biz.dfch.CS.Testing.nuspec`
  * [x] `AssemblyVersion.cs`
* [x] Execute unit tests
* [x] Release version `2.0`

**Comment by rufer7** [comment]
https://stackoverflow.com/questions/42621439/difference-between-microsoft-visualstudio-testplatform-testframework-and-microso

**Comment by rufer7** [comment]
@dfch I resolved this issue and released version `2.0.0` to NuGet.org.
